Add missing GStreamer alsamixer dependency
Fix for fail to start on Debian Stretch.

```
Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 169, in <module>
    main()
  File "/usr/bin/sugar-activity", line 164, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
  File "/usr/bin/sugar-activity", line 42, in create_activity_instance
    activity = constructor(handle)
  File "/usr/share/sugar/activities/Measure.activity/measure.py", line 142, in __init__
    self.audiograb = AudioGrab_Unknown(self.wave.new_buffer, self)
  File "/usr/share/sugar/activities/Measure.activity/audiograb.py", line 112, in __init__
    self._query_mixer()
  File "/usr/share/sugar/activities/Measure.activity/audiograb.py", line 165, in _query_mixer
    self._mixer = gst.element_factory_make('alsamixer')
gst.ElementNotFoundError: alsamixer
```